//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `serviceAjoutSupression.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let ModuleAjoutSupp = _ModuleRegistry.module("ModuleAjoutSupp");

    const iceC_ModuleAjoutSupp_MonInterface_ids = [
        "::Ice::Object",
        "::ModuleAjoutSupp::MonInterface"
    ];

    ModuleAjoutSupp.MonInterface = class extends Ice.Object
    {
    };

    ModuleAjoutSupp.MonInterfacePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(ModuleAjoutSupp.MonInterface, ModuleAjoutSupp.MonInterfacePrx, iceC_ModuleAjoutSupp_MonInterface_ids, 1,
    {
        "addSong": [, , , , [7], [[7], [7], [7], [7], [7]], , , , ],
        "deleteSong": [, , , , [7], [[7]], , , , ]
    });
    exports.ModuleAjoutSupp = ModuleAjoutSupp;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
